{
 "title": "OpenTelemetry Service",
 "description": "Instrument services with OpenTelemetry and send traces, metrics, and logs to Tempo, a Prometheus database like Mimir, and Loki.",
 "tags": [
  "otel",
  "opentelemetry",
  "service"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Metrics", "query": "prometheus" },
   { "name": "tempo_datasource", "label": "Traces", "query": "tempo" },
   { "name": "loki_datasource", "label": "Logs", "query": "loki" },
   {
    "name": "service_namespace",
    "label": "service.namespace",
    "query": {}
   },
   {
    "name": "service_name",
    "label": "service.name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "#  OpenTelemetry service ${service_namespace}/${service_name}"
   }
  },
  { "title": "Server HTTP RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "HTTP Endpoints Aggregation.\nhttps://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(http_server_request_duration_seconds_bucket{job=\"$service_namespace/$service_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, job) (rate(http_server_request_duration_seconds_bucket{job=\"$service_namespace/$service_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "avg by(job) (rate(http_server_request_duration_seconds_sum{job=\"$service_namespace/$service_name\"}[$__rate_interval])) / avg by(job) (rate(http_server_request_duration_seconds_count{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "HTTP Endpoints aggregation. Percentage of 5xx HTTP response status code.\nhttps://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without(http_response_status_code, error_type, instance) (rate(http_server_request_duration_seconds_count{job=\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval])) * 100) / sum without(http_response_status_code, error_type, instance) (rate(http_server_request_duration_seconds_count{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "HTTP Endpoints aggregation.\nhttps://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval])) by (job)) * $__interval_ms / 1000",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Server gRPC RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "gRPC Endpoints aggregation.\nhttps://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(rpc_server_duration_milliseconds_bucket{job=\"$service_namespace/$service_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, job) (rate(rpc_server_duration_milliseconds_bucket{job=\"$service_namespace/$service_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "avg by(job) (rate(rpc_server_duration_milliseconds_sum{job=\"$service_namespace/$service_name\"}[$__rate_interval])) / avg by(job) (rate(rpc_server_duration_milliseconds_count{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "gRPC Endpoints aggregation.\nPercentage of response with gRPC status code != 0.\nhttps://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum without (rpc_grpc_status_code, instance) (rate(rpc_server_duration_milliseconds_count{job=\"$service_namespace/$service_name\", rpc_grpc_status_code!=\"0\"}[$__rate_interval])) * 100) / sum without (rpc_grpc_status_code, instance) (rate(rpc_server_duration_milliseconds_count{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "gRPC Endpoints aggregation.\nhttps://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(rpc_server_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval])) by (job)) * $__interval_ms / 1000",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Inbound Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HTTP Operations",
   "type": "table",
   "description": "Inbound HTTP operations of the service (aka HTTP endpoints).\nhttps://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(http_server_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n            )\n        )\n    )",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "\n        histogram_quantile(\n            0.99,\n            sum by (le, operation) (\n                label_join(\n                rate(http_server_request_duration_seconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n                \"operation\",\n                \" \",\n                \"http_request_method\",\n                \"http_route\"\n                )\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "gRPC Operations",
   "type": "table",
   "description": "Inbound gRPC operations of the service (aka gRPC endpoints).\nSpecific to gRPC vs. other RPC technologies due to the usage of the rpc.grpc.status_code\nhttps://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#metric-rpcserverduration",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "\nsum by (operation) (\n    label_join(\n        rate(rpc_server_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n        \"operation\",\n        \"/\",\n        \"rpc_service\",\n        \"rpc_method\"\n    )\n)\n    ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n        sum by (operation) (\n            label_join(\n                rate(rpc_server_duration_milliseconds_count{job=~\"$service_namespace/$service_name\", rpc_grpc_status_code!=\"0\"}[$__rate_interval]),\n                \"operation\",\n                \"/\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n     / \n        sum by (operation) (\n            label_join(\n                rate(rpc_server_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \"/\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n    ) or (0 * \n        sum by (operation) (\n            label_join(\n                rate(rpc_server_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"operation\",\n                \"/\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n    )\n    ",
     "legendFormat": "__auto"
    },
    {
     "expr": "\n        histogram_quantile(\n            0.99,\n            sum by (le, operation) (\n                label_join(\n                rate(rpc_server_duration_milliseconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n                \"operation\",\n                \"/\",\n                \"rpc_service\",\n                \"rpc_method\"\n                )\n            )\n        )\n    ",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Outbound Services and Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Outbound HTTP Services",
   "type": "table",
   "description": "HTTP calls made by the service. Broken done by remote server.address and by http.request.method\nhttps://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpclientrequestduration",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=~\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(http_client_request_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \" \",\n                \"server_address\",\n                \"http_request_method\",\n                \"url_template\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(http_client_request_duration_seconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n        \"outbound_service\",\n        \" \",\n        \"server_address\",\n        \"http_request_method\",\n        \"url_template\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{http_request_method}} {{url_template}}"
    }
   ]
  },
  {
   "title": "Outbound Databases",
   "type": "table",
   "description": "DB calls made by the service.\nhttps://opentelemetry.io/docs/specs/semconv/database/database-metrics/#metric-dbclientoperationduration",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (database) (\n    label_join(\n        rate(db_client_operation_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n        \"database\",\n        \"/\",\n        \"server_address\",\n        \"db_namespace\"\n    )\n)\n    ",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "(\n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{job=~\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"server_address\",\n                \"db_namespace\"\n            )\n        )\n     / \n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"server_address\",\n                \"db_namespace\"\n            )\n        )\n    ) or (0 * \n        sum by (database) (\n            label_join(\n                rate(db_client_operation_duration_seconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"database\",\n                \"/\",\n                \"server_address\",\n                \"db_namespace\"\n            )\n        )\n    )",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, database) (\n        label_join(\n        rate(db_client_operation_duration_seconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n            \"database\",\n            \"/\",\n            \"server_address\",\n            \"db_namespace\"\n        )\n    )\n)",
     "legendFormat": "{{server_address}} {{db_namespace}}"
    }
   ]
  },
  {
   "title": "Outbound gRPC Services",
   "type": "table",
   "description": "gRPC calls made by the service.\nSpecific to gRPC vs other RPC technologies due to the usage of the grpc.status.code attribute.\nhttps://opentelemetry.io/docs/specs/semconv/rpc/rpc-metrics/#rpc-client",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "\n        sum by (outbound_service) (\n            label_join(\n                rate(rpc_client_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \"/\",\n                \"server_address\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n    ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n        sum by (outbound_service) (\n            label_join(\n                rate(rpc_client_duration_milliseconds_count{job=~\"$service_namespace/$service_name\", http_response_status_code=~\"5..\"}[$__rate_interval]),\n                \"outbound_service\",\n                \"/\",\n                \"server_address\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n     / \n        sum by (outbound_service) (\n            label_join(\n                rate(rpc_client_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \"/\",\n                \"server_address\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n    ) or (0 * \n        sum by (outbound_service) (\n            label_join(\n                rate(rpc_client_duration_milliseconds_count{job=~\"$service_namespace/$service_name\"}[$__rate_interval]),\n                \"outbound_service\",\n                \"/\",\n                \"server_address\",\n                \"rpc_service\",\n                \"rpc_method\"\n            )\n        )\n    )",
     "legendFormat": "__auto"
    },
    {
     "expr": "\nhistogram_quantile(\n    0.99,\n    sum by (le, outbound_service) (\n        label_join(\n        rate(rpc_client_duration_milliseconds_bucket{job=~\"$service_namespace/$service_name\"}[5m]),\n        \"outbound_service\",\n        \"/\",\n        \"server_address\",\n        \"rpc_service\",\n        \"rpc_method\"\n        )\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "logs",
   "description": "Logs for the service",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$service_name\", service_namespace=\"$service_namespace\"} | line_format `\u001b[1m{{if .level }}{{alignRight 5 .level}}{{else if .severity_text}}{{alignRight 5 .severity_text}}{{end}}\u001b[0m \u001b[90m[{{alignRight 10 .service_instance_id}}{{if .thread_name}}/{{alignRight 20 .thread_name}}{{else if eq \"java\" .telemetry_sdk_language }}                    {{end}}]\u001b[0m \u001b[36m{{if .scope_name }}{{alignRight 40 .scope_name}}{{end}}\u001b[0m {{__line__}} {{if .trace_id}} \u001b[37m\u001b[3m[trace_id={{.trace_id}}]{{end}}`"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "table",
   "description": "Traces containing a span emitted by the service",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 47 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service_name" ],
       "valueType": "string"
      },
      {
       "id": "6997e808",
       "operator": "=",
       "scope": "resource",
       "tag": "deployment.environment.name",
       "value": [ "$deployment_environment_name" ],
       "valueType": "string"
      },
      {
       "id": "e9f0e855",
       "operator": "=",
       "scope": "resource",
       "tag": "service.namespace",
       "value": [ "$service_namespace" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"$service_name\" && resource.service.namespace=\"$service_namespace\"} | select(status)",
     "tableType": "spans"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "JVM",
   "type": "table",
   "description": "For JVM based services like Java or Kotlin, the JVM metrics",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_cpu_recent_utilization_ratio{job=\"$service_namespace/$service_name\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(instance) (rate(jvm_gc_duration_seconds_sum{job=\"$service_namespace/$service_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}